Repository tail-unica/hopwise, pull requests merged in 2025-03, with the labels that each got.

#155 fix notebook
  run_example/format_kg_aware_recsys_embs.ipynb
Labels: enhancement

#160 Consumer metrics fix
  hopwise/data/dataset/kg_dataset.py
  hopwise/evaluator/base_metric.py
  hopwise/evaluator/collector.py
  hopwise/evaluator/metrics.py
  hopwise/trainer/hf_path_trainer.py
  hopwise/trainer/trainer.py
Labels: bug

#164 162 eval dataloader revision
  build/lib/hopwise/__init__.py
  hopwise/data/dataloader/general_dataloader.py
  hopwise/data/dataloader/knowledge_dataloader.py
  hopwise/trainer/trainer.py
Labels: bug, enhancement

#169 156 guarantee installation and running on windows
  .github/workflows/uv_sync_cpu.yml
  .github/workflows/uv_sync_cu118.yml
  .github/workflows/uv_sync_cu121.yml
  .github/workflows/uv_sync_cu124.yml
  .gitignore
  README.md
  hopwise/__init__.py
  hopwise/config/configurator.py
  hopwise/data/dataset/dataset.py
  hopwise/model/general_recommender/gcmc.py
  hopwise/model/general_recommender/lightgcn.py
  hopwise/model/general_recommender/ncl.py
  hopwise/model/general_recommender/ngcf.py
  hopwise/trainer/trainer.py
  pyproject.toml
  requirements.txt
Labels: enhancement

#170 148 integrate kgglm with link prediction task and kg splitting
  .github/workflows/uv_sync_cu121.yml
  .gitignore
  hopwise/config/configurator.py
  hopwise/data/dataloader/knowledge_dataloader.py
  hopwise/data/dataset/customized_dataset.py
  hopwise/data/dataset/kg_dataset.py
  hopwise/data/dataset/kg_path_dataset.py
  hopwise/model/layers.py
  hopwise/model/path_language_modeling_recommender/__init__.py
  hopwise/model/path_language_modeling_recommender/kgglm.py
  hopwise/model/path_language_modeling_recommender/pearlm.py
  hopwise/properties/dataset/ml-100k.yaml
  hopwise/properties/dataset/sample.yaml
  hopwise/properties/model/KGGLM.yaml
  hopwise/properties/model/PEARLM.yaml
  hopwise/properties/quick_start_config/knowledge_path_base.yaml
  hopwise/trainer/hf_path_trainer.py
  hopwise/trainer/trainer.py
  hopwise/utils/utils.py
  pyproject.toml
  tests/data/test_dataloader.py
  tests/data/test_dataset.py
Labels: bug, enhancement
